- name: install wget
  yum:
    name: wget
    state: latest

- name: get binaries
  get_url:
    url: "{{ item.name }}"
    dest: "{{ item.fn }}"
    mode: 0550
  with_items:
  - { name: 'https://pkg.cfssl.org/R1.2/cfssl_linux-amd64', fn: '/usr/local/bin/cfssl' }
  - { name: 'https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64', fn: '/usr/local/bin/cfssljson' }

